# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from molinkv1.comm import molink_pb2 as molink__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in molink_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MolinkServiceStub(object):
    """The MoLink communication service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinPipeline = channel.unary_unary(
                '/molink.MolinkService/JoinPipeline',
                request_serializer=molink__pb2.NodeInfo.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/molink.MolinkService/GetTopology',
                request_serializer=molink__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=molink__pb2.PipelineTopology.FromString,
                _registered_method=True)
        self.PushIntermediateTensors = channel.unary_unary(
                '/molink.MolinkService/PushIntermediateTensors',
                request_serializer=molink__pb2.GrpcRequestData.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.PushSamplerOutput = channel.unary_unary(
                '/molink.MolinkService/PushSamplerOutput',
                request_serializer=molink__pb2.SamplerOutput.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.ExecuteWorkerStep = channel.unary_unary(
                '/molink.MolinkService/ExecuteWorkerStep',
                request_serializer=molink__pb2.GrpcTriggerRequest.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.SyncKVCacheConfig = channel.unary_unary(
                '/molink.MolinkService/SyncKVCacheConfig',
                request_serializer=molink__pb2.KVCacheConfigData.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.InitializeModel = channel.unary_unary(
                '/molink.MolinkService/InitializeModel',
                request_serializer=molink__pb2.ModelConfigData.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/molink.MolinkService/HealthCheck',
                request_serializer=molink__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=molink__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/molink.MolinkService/Shutdown',
                request_serializer=molink__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=molink__pb2.GrpcResponseData.FromString,
                _registered_method=True)


class MolinkServiceServicer(object):
    """The MoLink communication service
    """

    def JoinPipeline(self, request, context):
        """Join the pipeline as a worker node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Get current pipeline topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushIntermediateTensors(self, request, context):
        """Push intermediate tensors to next pipeline stage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushSamplerOutput(self, request, context):
        """Return sampler output to head node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorkerStep(self, request, context):
        """Trigger worker to execute a step
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncKVCacheConfig(self, request, context):
        """Synchronize KV cache configuration across nodes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeModel(self, request, context):
        """Initialize model on worker node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MolinkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinPipeline,
                    request_deserializer=molink__pb2.NodeInfo.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=molink__pb2.HealthCheckRequest.FromString,
                    response_serializer=molink__pb2.PipelineTopology.SerializeToString,
            ),
            'PushIntermediateTensors': grpc.unary_unary_rpc_method_handler(
                    servicer.PushIntermediateTensors,
                    request_deserializer=molink__pb2.GrpcRequestData.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'PushSamplerOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.PushSamplerOutput,
                    request_deserializer=molink__pb2.SamplerOutput.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'ExecuteWorkerStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorkerStep,
                    request_deserializer=molink__pb2.GrpcTriggerRequest.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'SyncKVCacheConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncKVCacheConfig,
                    request_deserializer=molink__pb2.KVCacheConfigData.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'InitializeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeModel,
                    request_deserializer=molink__pb2.ModelConfigData.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=molink__pb2.HealthCheckRequest.FromString,
                    response_serializer=molink__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=molink__pb2.HealthCheckRequest.FromString,
                    response_serializer=molink__pb2.GrpcResponseData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'molink.MolinkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('molink.MolinkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MolinkService(object):
    """The MoLink communication service
    """

    @staticmethod
    def JoinPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/JoinPipeline',
            molink__pb2.NodeInfo.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/GetTopology',
            molink__pb2.HealthCheckRequest.SerializeToString,
            molink__pb2.PipelineTopology.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushIntermediateTensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/PushIntermediateTensors',
            molink__pb2.GrpcRequestData.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushSamplerOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/PushSamplerOutput',
            molink__pb2.SamplerOutput.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorkerStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/ExecuteWorkerStep',
            molink__pb2.GrpcTriggerRequest.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncKVCacheConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/SyncKVCacheConfig',
            molink__pb2.KVCacheConfigData.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/InitializeModel',
            molink__pb2.ModelConfigData.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/HealthCheck',
            molink__pb2.HealthCheckRequest.SerializeToString,
            molink__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/molink.MolinkService/Shutdown',
            molink__pb2.HealthCheckRequest.SerializeToString,
            molink__pb2.GrpcResponseData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
